FROM python:3.7-slim

ARG CONSUMER_SECRET
ARG CONSUMER_KEY
ARG ACCESS_TOKEN
ARG ACCESS_TOKEN_SECRET

ENV CONSUMER_SECRET=${CONSUMER_SECRET}
ENV CONSUMER_KEY=${CONSUMER_KEY}
ENV ACCESS_TOKEN=${ACCESS_TOKEN}
ENV ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}

COPY . ./app

WORKDIR ./app

RUN pip install --upgrade pip && pip install -r requirements.txt

CMD python app.py